{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggh4x
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggh4x_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggh4x/ggh4x_{{ version }}.tar.gz
  sha256: d8fcc030ee7508126c22ad846228e49067c4764293bb12cc606b08c665705f87

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-s7
    - r-cli
    - r-ggplot2 >=3.5.2
    - r-gtable
    - r-lifecycle
    - r-rlang >=1.1.0
    - r-scales
    - r-vctrs >=0.5.0
  run:
    - r-base
    - r-s7
    - r-cli
    - r-ggplot2 >=3.5.2
    - r-gtable
    - r-lifecycle
    - r-rlang >=1.1.0
    - r-scales
    - r-vctrs >=0.5.0

test:
  commands:
    - $R -e "library('ggh4x')"           # [not win]
    - "\"%R%\" -e \"library('ggh4x')\""  # [win]

about:
  home: https://github.com/teunbrand/ggh4x
  license: MIT
  summary: A 'ggplot2' extension that does a variety of little helpful things.  The package extends 'ggplot2' facets through customisation, by setting individual scales per panel, resizing panels and providing nested facets.  Also allows multiple colour and fill scales per plot. Also hosts a smaller collection of stats,
    geoms and axis guides.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf
